config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :listings do
      resources :orders
  end

  root 'listings#index'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"


  # static_pages
  controller :static_pages do
    get :trouble
    get :seller_center
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord

  belongs_to :user
  has_many :orders

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

  validates :name, :description, :price, :image, presence: true
  validates :name, length: { minimum:15 }
  validates :description, length: { minimum:500, maximum:3500 }
  validates :price, numericality: { greater_than: 0 }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 1.megabytes

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
  validates :address, :city, :state, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :confirmable, password_length: 8..15
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :seller]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /seller
  def seller
   @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    if @listing.save
      redirect_to @listing, notice: 'Listing was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /listings/1
  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: 'Listing was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /listings/1
  def destroy
    @listing.destroy
    redirect_to listings_url, notice: 'Listing was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
       if current_user.id != @listing.user_id
         redirect_to root_url, alert: "Whops! You are not authorized. This is not your listing."
       end
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET  /sales
  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  # GET /purchases
  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders
  def index
    @orders = Order.all
  end

  # GET /orders/1
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user
    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    if @order.save
      redirect_to root_url, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:seller_center]

  def trouble
  end

  def seller_center
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable font-main">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Storeapp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="https://fonts.googleapis.com/css?family=Barrio|Cabin|Work+Sans:300" rel="stylesheet">
    <link rel="shortcut icon" href="https://s8.postimg.org/wqyi3jeqd/fav.png"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navigation/navbar' %>
      <%= render 'layouts/flash' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing, html: { multipart: true } do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation"><hr>
      <h4 class="font-main"><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved </h4>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li class="font-for-links"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <hr>
  <div class="form-group">
    <%= f.label :name, class: 'font-main' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image, class: 'font-main' %>
    <%= f.file_field :image, class: 'form-control font-main' %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'font-main' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price, class: 'font-main' %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success form-control font-main" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1 class="font-main label-color">Editing Listing</h1>

<%= render 'form', listing: @listing %>

<br/>
<center>
  <div class="bottom-margin">
    <b>
      <%= button_to "Delete Listing", listing_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger form-control' %></p>
    </b>
  </div>
</center>

app/views/listings/index.html.erb
<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <div class="caption text-align">

            <%= link_to image_tag(listing.image.url), listing %>
            <h3 class = "font-for-links"><b><%= listing.name %></b></h4>

            <p>
              <h5>
                <%= truncate(listing.description, length:175, class: "font-main") %>... <%= link_to 'See more', listing, class: "font-for-links" %>
              </h5>
            </p>

            <h5>
              <p class = "font-for-links"><b>
               <%= number_to_currency(listing.price) %>
             </b></p>
           </h5>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/listings/new.html.erb
<h1 class="font-main label-color">Add New Item.</h1>

<%= render 'form', listing: @listing %>

<br/>
<center>
  <div class="bottom-margin">
    <%= link_to 'Back', listings_path, class: 'font-for-links' %>
  </div>
</center>

app/views/listings/seller.html.erb
<% if current_user.listings.present? %>

  <div class="center">
    <div class="row">
      <% @listings.each do |listing| %>
        <div class="col-md-4">
          <div class="thumbnail">
            <div class="caption text-align">

              <%= link_to image_tag(listing.image.url), listing %>
              <h3 class = "font-for-links"><b><%= listing.name %></b></h4>

              <p>
                <h5>
                  <%= truncate(listing.description, length:175, class: "font-main") %>... <%= link_to 'See more', listing, class: "font-for-links" %>
                </h5>
              </p>

              <h5>
                <p class = "font-for-links"><b>
                 <%= number_to_currency(listing.price) %>
               </b></p>
             </h5>
             <hr>
             <h5><center>
               <p class = "font-for-links"><b>
                 <%= link_to 'Manage Listing', edit_listing_path(listing), class: "font-for-links" %>
              </b></p>
            <center></h5>

            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <% else %>

    <h3 class="font-main center-align">
      You haven't listed any item yet, Start selling now! <b><%= link_to 'Create New Listing', new_listing_path, class: 'font-for-links' %>
    </h3>

  <% end %>

app/views/listings/show.html.erb
<div class = "col-md-13">
  <div class="jumbotron">
    <div class="text-align">
      <div class="col-md-12">

       <div class="col-md-4 top-s">
         <%= image_tag @listing.image.url(:medium) %>
       </div>

       <div class="col-md-8">
          <p>
            <b>
             <h3 class = "font-for-links">
               <%= @listing.name %>
             </h3>
            </b>
          </p>

          <p>
            <b>
             <h5 class = "font-main">
               Sold by - <%= link_to @listing.user.name, '#', class: 'font-for-links' %>
             </h3>
            </b>
          </h5>

          <p>
            <b>
             <h5 class = "font-for-links">
               <%= number_to_currency(@listing.price) %>
             </h5>
            </b>
          </p>

          <p>
            <h4 class = "font-main">
              <b>Product Details</b> - <%= @listing.description %>
            </h4>
          </p>

          <p>
            <h4 class = "font-main">
              <%= link_to 'Buy', new_listing_order_path(@listing), class: "btn btn-success form-control font-main"%>
            </h4>
          </p>

          <p>
            <h6>
              <% if current_user.id == @listing.user_id %>
                <%= link_to 'Edit', edit_listing_path(@listing), class: "font-for-links" %>
              <% end %>
            </h6>
          </p>

        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/navigation/_footer.html.erb
<div class="footer">

  <div class="navbar navbar-default navbar-bottom">
    <div class="container">
      <p class="navbar-text pull-left">© 2017 - Ankesh Samarth
      </p>
    </div>
  </div>

</div>

app/views/navigation/_navbar.html.erb
<nav class="navbar navbar-default down-s" >
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand font-one" href="/">storeapp</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right font-for-links">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li class = "content-form"><%= link_to "Your Profile", '#' %></li>
                <li role="separator" class="divider"></li>
                <li class = "content-form"><%= link_to "Seller Center", seller_center_path %></li>
                <li class = "content-form"><%= link_to "Buyer Center", purchases_path %></li>
                <li class = "content-form"><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li class = "content-form"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li class = "content-form"><%= link_to "Create New Account", new_user_registration_path %></li>
            <li class = "content-form"><%= link_to "Login", new_user_session_path  %></li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/orders/_form.html.erb
<%= form_for([@listing, @order]) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2 class="font-main"><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li class="font-for-links"><%= message %></li>
      <% end %>
      </ul>
    </div>
    <hr>
  <% end %>

  <div class="form-group">
    <%= f.label :address, class: 'font-main' %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :city, class: 'font-main' %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :state, class: 'font-main' %>
    <%= f.text_field :state, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success form-control font-main' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h3 class="font-main">New Order</h3><hr>

<%= render 'form', order: @order %>

<br/>
<br/>
<center>
  <%= link_to 'Cancle', listing_orders_path, class: 'font-for-links' %>
<center>

app/views/orders/purchases.html.erb
<% if @orders.present? %>
  <h2 class="font-main">Your Purchase History</h2>
  <hr>

  <table class="table table-striped table-bordered font-main">
    <tr>
      <th class="center">Image</th>
      <th class="center">Item</th>
      <th class="center">Price</th>
      <th class="center">Seller</th>
      <th class="center">Date Purchased</th>
    </tr>

    <% @orders.each do |order| %>
      <tr>
        <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
        <td class="center"><%= order.listing.name %></td>
        <td class="center"><%= number_to_currency(order.listing.price) %></td>
        <td class="center"><%= order.seller.name %></td>
        <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <center>
    <h1 class="font-main center-align"> You haven't purchased any items yet, <%= link_to 'Purchase now', root_path, class: 'font-for-links' %>
      </h1>
  </center>
<% end %>

app/views/orders/sales.html.erb
<% if @orders.present? %>
  <h2 class="font-main">Your Sales History</h2><hr>

  <table class="table table-striped table-bordered">
    <tr>
      <th class="center font-main">Image</th>
      <th class="center font-main">Item</th>
      <th class="center font-main">Price</th>
      <th class="center font-main">Customer</th>
      <th class="center font-main">Date Sold</th>
    </tr>

    <% @orders.each do |order| %>
      <tr>
        <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
        <td class="center"><%= order.listing.name %></td>
        <td class="center"><%= number_to_currency(order.listing.price) %></td>
        <td class="center"><%= order.buyer.name %></td>
        <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <center>
    <h1 class="font-main center-align"> Your sales history is empty.
      <br>
       <%= link_to 'Add new item', new_listing_path, class: 'font-for-links' %>
        <br>
        <%= link_to 'Manage your listings', seller_path, class: 'font-for-links' %>
    </h1>
  </center>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/static_pages/seller_center.html.erb
<div class="col-md-12 center-align">

  <div class="col-md-4">
    <div class="jumbotron">
      <h4 class="font-main">Sale new item,<br><%= link_to 'Click here', new_listing_path, class: 'font-for-links' %>
    </div>
  </div>

  <div class="col-md-4">
    <div class="jumbotron">
        <h4 class="font-main">Manage your listings,<br><%= link_to 'Click here', seller_path, class: 'font-for-links' %>
    </div>
  </div>

  <div class="col-md-4">
    <div class="jumbotron">
      <h4 class="font-main">Check your sales,<br><%= link_to 'Click here', sales_path, class: 'font-for-links' %>
    </div>
  </div>

</div>

app/views/static_pages/trouble.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="jumbotron">
    <div class="container">
      <center><b><h3 class="font-for-links">Can't sign in to your Account.</h3></b></center>
      <hr>
      <center><b><h3 class="font-main">Select the issue.</h3></b><hr>
        <%= link_to "Forgot your password?", new_user_password_path, class: 'font-for-links' %><br /><hr>
        <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path, class: 'font-for-links' %><br /><hr>
        <%= link_to "Didn't receive unlock instructions?", '#', class: 'font-for-links' %><br /><hr>
        <%= link_to "Something else", "#", class: 'font-for-links' %><br /><hr>
      </center>
    </div>
  </div>
</div>